<?php

/**
 * @file
 * Primary module hooks for Multiplex module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function multiplex_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the multiplex module.
    case 'help.page.multiplex':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Multiplex module: redirect to different locations based on rules.') . '</p>';
      return $output;
    default:
  }
}

function multiplex_get_visitor_cookie_value() {
  $settings_name = 'multiplex.settings';
  if (\Drupal::moduleHandler()->moduleExists('guest_upload')) {
    $settings_name = 'guest_upload.settings';
  }
  $cookie = \Drupal::config($settings_name)->get('cookie');
  $who = $_COOKIE[$cookie] ?? '';
  return $who;
}

/**
 * Attach our Javascript
 */
function multiplex_page_attachments(array &$page) {
  //if (!\Drupal::currentUser()->hasPermission('some permission not yet defined')) {
  //  return;
  //}

  $who = multiplex_get_visitor_cookie_value();
  if (empty($who)) {
    return;
  }

  $config = \Drupal::config('multiplex.settings');

  $basePath = "/" . drupal_get_path('module', 'multiplex') . "/";
  $items = [
    'lantern' => [
      'url' => $basePath . 'images/objects/lantern.png',
      'alt' => 'The green spooky lantern of magic',
      'fixed_order' => 1,
    ],
    'pumpkin' => [
      'url' => $basePath . 'images/objects/pumpkin.png',
      'alt' => 'The enchanted pumpkin',
      'fixed_order' => 2,
    ],
    'top_hat' => [
      'url' => $basePath . 'images/objects/top_hat.png',
      'alt' => 'A musty old hat',
      'fixed_order' => 3,
    ],
    'old_key' => [
      'url' => $basePath . 'images/objects/old_key.png',
      'alt' => 'A mysterious key, I wonder what it goes to',
      'fixed_order' => 4,
    ]
  ];


  $computed_settings = [
    'items' => $items // $config->get('cookie'),
  ];

  $page['#attached']['library'][] = 'multiplex/multiplex';
  $page['#attached']['drupalSettings']['multiplex'] = $computed_settings;
}
